// Templates that ship with the server. They're plain data in the template format, so they double as examples:
// `notion_template` action=get shows each one, and a saved template with the same name replaces it.
export const BUILTIN_TEMPLATES: unknown[] = [
  {
    version: 1,
    name: "weekly-executive-report",
    description: "A one-page weekly update: headline, numbers, wins, risks, decisions needed, and next week. Numbers can come from a database.",
    variables: {
      week_of: { type: "date", required: true, description: "Monday of the week, YYYY-MM-DD" },
      headline: { type: "string", required: true, description: "One sentence: the state of things" },
      status: { type: "string", default: "On track", description: "On track, At risk, or Off track" },
      kpis: { type: "list", default: [], description: "[{label, value}] or [{label, metric: {database, value: \"count\" | \"sum:Prop\", where}}]" },
      wins: { type: "list", default: [], description: "Short sentences" },
      risks: { type: "list", default: [], description: "[{risk, owner, mitigation}]" },
      decisions: { type: "list", default: [], description: "Decisions needed from leadership" },
      next_week: { type: "list", default: [] },
      trend: { type: "list", default: [], description: "Optional chart rows [{x, y, series?}]" },
      trend_title: { type: "string", default: "Trend" },
    },
    parts: {
      bullets: [{ each: "items", as: "item", blocks: [{ markdown: "- {{item}}" }] }],
    },
    title: "Weekly update · {{week_of}}",
    icon: "📈",
    blocks: [
      {
        if: { var: "status", equals: "On track" },
        then: [{ callout: "**{{status}}** · {{headline}}", icon: "🟢", color: "green_background" }],
        else: [
          {
            if: { var: "status", equals: "At risk" },
            then: [{ callout: "**{{status}}** · {{headline}}", icon: "🟡", color: "yellow_background" }],
            else: [{ callout: "**{{status}}** · {{headline}}", icon: "🔴", color: "red_background" }],
          },
        ],
      },
      { if: "kpis", then: [{ heading: "Numbers" }, { kpis: "{{kpis}}" }] },
      { if: "trend", then: [{ chart: { spec: { type: "line", title: "{{trend_title}}" }, data: "{{trend}}", data_table: true } }] },
      { if: "wins", then: [{ heading: "Wins" }, { part: "bullets", with: { items: "{{wins}}" } }] },
      {
        if: "risks",
        then: [
          { heading: "Risks" },
          { each: "risks", as: "r", blocks: [{ callout: "**{{r.risk}}**\nOwner: {{r.owner}} · Mitigation: {{r.mitigation}}", icon: "⚠️", color: "orange_background" }] },
        ],
      },
      { if: "decisions", then: [{ heading: "Decisions needed" }, { each: "decisions", as: "d", blocks: [{ markdown: "- [ ] {{d}}" }] }] },
      { if: "next_week", then: [{ heading: "Next week" }, { part: "bullets", with: { items: "{{next_week}}" } }] },
      { slot: "notes" },
    ],
  },
  {
    version: 1,
    name: "content-brief",
    description: "A brief for one piece of content: goal, audience, key messages, outline, sources, and a review checklist.",
    variables: {
      title: { type: "string", required: true },
      format: { type: "string", default: "Blog post" },
      goal: { type: "string", required: true },
      audience: { type: "string", required: true },
      due: { type: "date" },
      owner: { type: "string" },
      messages: { type: "list", default: [], description: "Key messages, most important first" },
      outline: { type: "list", default: [], description: "[{section, points: [...]}]" },
      keywords: { type: "list", default: [] },
      sources: { type: "list", default: [], description: "Links or citations" },
    },
    title: "Brief: {{title}}",
    icon: "📝",
    blocks: [
      {
        columns: [
          [{ callout: "**Format**\n{{format}}", icon: "🧾" }],
          [{ if: "due", then: [{ callout: "**Due**\n{{due}}", icon: "📅" }], else: [{ callout: "**Due**\nNot set", icon: "📅" }] }],
          [{ if: "owner", then: [{ callout: "**Owner**\n{{owner}}", icon: "👤" }], else: [{ callout: "**Owner**\nUnassigned", icon: "👤" }] }],
        ],
      },
      { heading: "Goal" },
      { markdown: "{{goal}}" },
      { heading: "Audience" },
      { markdown: "{{audience}}" },
      { if: "messages", then: [{ heading: "Key messages" }, { each: "messages", as: "m", blocks: [{ markdown: "{{m_index}}. {{m}}" }] }] },
      {
        if: "outline",
        then: [
          { heading: "Outline" },
          { each: "outline", as: "s", blocks: [{ toggle: "{{s.section}}", children: [{ each: "s.points", as: "p", blocks: [{ markdown: "- {{p}}" }] }] }] },
        ],
      },
      { if: "keywords", then: [{ heading: "Keywords", level: 3 }, { each: "keywords", as: "k", blocks: [{ markdown: "- `{{k}}`" }] }] },
      { if: "sources", then: [{ heading: "Sources", level: 3 }, { each: "sources", as: "src", blocks: [{ markdown: "- {{src}}" }] }] },
      { heading: "Review checklist" },
      { markdown: "- [ ] Goal and audience are clear in the first paragraph\n- [ ] Every key message appears\n- [ ] Facts checked against sources\n- [ ] Links work\n- [ ] Approved by owner" },
      { slot: "draft", default: [{ heading: "Draft" }, { markdown: "Write here." }] },
    ],
  },
  {
    version: 1,
    name: "launch-plan",
    description: "A launch plan: summary, goals, milestones (with a Gantt chart), owners, risks, and a go/no-go checklist.",
    variables: {
      product: { type: "string", required: true },
      launch_date: { type: "date", required: true },
      summary: { type: "string", required: true },
      goals: { type: "list", default: [], description: "[{goal, metric, target}]" },
      milestones: { type: "list", default: [], description: "[{name, start, end, owner, status: done|active|crit|null}]" },
      risks: { type: "list", default: [], description: "[{risk, likelihood, mitigation}]" },
      tracker: { type: "string", description: "Optional database of launch tasks; adds a live board view" },
      status_property: { type: "string", default: "Status" },
    },
    title: "Launch plan: {{product}}",
    icon: "🚀",
    blocks: [
      { callout: "Launching **{{product}}** on **{{launch_date}}**. {{summary}}", icon: "🚀", color: "blue_background" },
      {
        if: "goals",
        then: [
          { heading: "Goals" },
          { each: "goals", as: "g", blocks: [{ markdown: "- **{{g.goal}}**: {{g.metric}} → {{g.target}}" }] },
        ],
      },
      {
        if: "milestones",
        then: [
          { heading: "Timeline" },
          { gantt: { title: "{{product}} launch", tasks: "{{milestones}}" } },
          { toggle: "Milestones and owners", children: [{ each: "milestones", as: "m", blocks: [{ markdown: "- {{m.name}}: {{m.start}} → {{m.end}} ({{m.owner}})" }] }] },
        ],
      },
      { if: "tracker", then: [{ heading: "Tasks" }, { view: { database: "{{tracker}}", view: { name: "Launch board", type: "board", group_by: "{{status_property}}" } } }] },
      { if: "risks", then: [{ heading: "Risks" }, { each: "risks", as: "r", blocks: [{ callout: "**{{r.risk}}** ({{r.likelihood}})\n{{r.mitigation}}", icon: "⚠️", color: "orange_background" }] }] },
      { heading: "Go / no-go" },
      { markdown: "- [ ] Docs and help center updated\n- [ ] Support briefed\n- [ ] Monitoring and rollback plan ready\n- [ ] Announcement approved\n- [ ] Owners confirmed for launch day" },
      { slot: "notes" },
    ],
  },
  {
    version: 1,
    name: "research-dossier",
    description: "A research write-up: question, summary, key findings with evidence, method, open questions, and sources.",
    variables: {
      topic: { type: "string", required: true },
      question: { type: "string", required: true },
      summary: { type: "string", required: true, description: "The answer in a few sentences" },
      confidence: { type: "string", default: "Medium", description: "High, Medium, or Low" },
      findings: { type: "list", default: [], description: "[{finding, evidence, source}]" },
      method: { type: "string" },
      data: { type: "list", default: [], description: "Optional chart rows [{x, y, series?}]" },
      chart_type: { type: "string", default: "column" },
      chart_title: { type: "string", default: "Data" },
      open_questions: { type: "list", default: [] },
      sources: { type: "list", default: [] },
    },
    title: "Research: {{topic}}",
    icon: "🔎",
    blocks: [
      { callout: "**Question:** {{question}}", icon: "❓", color: "gray_background" },
      { heading: "Summary" },
      { markdown: "{{summary}}" },
      { markdown: "*Confidence: {{confidence}}*" },
      {
        if: "findings",
        then: [
          { heading: "Key findings" },
          { each: "findings", as: "f", blocks: [{ toggle: "{{f_index}}. {{f.finding}}", children: [{ markdown: "{{f.evidence}}" }, { markdown: "Source: {{f.source}}" }] }] },
        ],
      },
      { if: "data", then: [{ chart: { spec: { type: "column", title: "{{chart_title}}" }, data: "{{data}}", data_table: true } }] },
      { if: "method", then: [{ heading: "Method", level: 3 }, { markdown: "{{method}}" }] },
      { if: "open_questions", then: [{ heading: "Open questions", level: 3 }, { each: "open_questions", as: "q", blocks: [{ markdown: "- {{q}}" }] }] },
      { if: "sources", then: [{ heading: "Sources", level: 3 }, { each: "sources", as: "s", blocks: [{ markdown: "{{s_index}}. {{s}}" }] }] },
      { slot: "appendix" },
    ],
  },
];
